{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.appName }}-{{ .Values.environment }}"
  labels:
    app: "{{ .Values.appName }}-{{ .Values.environment }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: "service-{{ .Values.appName }}-{{ .Values.environment }}"
                port:
                  number: {{ .Values.externalPort }}
{{- end }}
