apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.appName }}-{{ .Values.environment }}
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Values.appName }}-{{ .Values.environment }}"
  ports:
    - protocol: TCP
      port: {{ .Values.externalPort }}
      targetPort: {{ .Values.targetPort }}