name: Build Helm Chart

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Helm
        uses: azure/setup-helm@v1
      
      - name: Build Helm chart
        run: |
          helm dependency update  
          helm package . -d ./docs
        
      - name: Generate index.yaml
        run: |
          helm repo index ./docs --url https://sebokoslav.github.io/web-app-chart/
        
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add --all
          git commit -m "Build helm chart"
          git push
